version: '1.0'
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  mysql:
    image: mysql
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./api/data/Mysql/database.sql:/docker-entrypoint-initdb.d/database.sql:ro
      - type: bind
        source: ./mysql_data
        target: /mysql_data/db
    environment:
      MYSQL_ROOT_PASSWORD: root

  neo4j:
    image: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
    environment:
      NEO4J_AUTH: neo4j/root
      NEO4J_dbms_security_auth__minimum__password__length: 4

volumes:
  mongo_data: 
  mysql_data:
  neo4j_data:

networks:
  your-network:
    driver: bridge
