version: '1.0'
services:
  # web:
  #   build:
  #     context: ./app
  #     dockerfile: Dockerfile
  #   ports:
  #     - "80:80"
  #   networks:
  #     - your-network
  #   depends_on:
  #     - mongo
  #     - mysql
    
  # api:
  #   build:
  #     context: ./api
  #     dockerfile: Dockerfile
  #   ports:
  #     - "4000:4000"
  #   depends_on:
  #     - mongo
  #     - mysql

  mongo:
    image: mongo
    ports:
      - "27017:27017"

    volumes:
      - mongo_data:/data/db

    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  mysql:
    image: mysql
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./api/data/Mysql/database.sql:/docker-entrypoint-initdb.d/database.sql:ro
      - type: bind
        source: ./mysql_data
        target: /mysql_data/db
    environment:
      MYSQL_ROOT_PASSWORD: root

volumes:
  mongo_data: 
  mysql_data:

networks:
  your-network:
    driver: bridge